# ==============================
# BANCO PostgreSQL (Docker / AWS RDS)
# Variáveis de ambiente definidas no docker-compose ou Elastic Beanstalk
# ==============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/checklistti}
spring.datasource.username=${DB_USER:tecnico}
spring.datasource.password=${DB_PASS:senha123}
spring.datasource.driver-class-name=org.postgresql.Driver
